In [ ]:
# approximate radius of earth in km
# example 278.546

# Take the data from the coal ash locations
# traverse the data from the soil samples --> while traversing array calculate distance between two points and keep the shortest one.
# Do this while it traverses all the arrays

from math import sin, cos, sqrt, atan2, radians
R = 6373.0

#lat1 = radians(52.2296756)
#lon1 = radians(21.0122287)
#lat2 = radians(52.406374)
#lon2 = radians(16.9251681)

lat1 = radians(36.2153)
lon1 = radians(-116.9411)
lat2 = radians(38.8689)
lon2 = radians(-84.2286)
dlon = lon2 - lon1
dlat = lat2 - lat1

a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
c = 2 * atan2(sqrt(a), sqrt(1 - a))

distance = R * c

print("Result:", distance)
print("Should be:", 278.546, "km")

Result: 2884.662330608657
Should be: 278.546 km

In [ ]:
import pandas as pd
data = pd.read_csv("CoalAshLatLong.csv")
data

     17.948232   -66.152032
0      27.7944     -82.4036
1      28.0809     -81.9256
2      28.4836     -81.1686
3      28.7087     -97.2083
4      28.7094     -98.4722
..         ...          ...
295   47.53015    -92.25007
296   47.53083   -90.911468
297    47.6794    -104.1533
298  63.855373  -148.950634
299        Lat         Long

[300 rows x 2 columns]

In [ ]:
"""from google.colab import drive
drive.mount('/content/drive')"""

KeyboardInterrupt: ignored

In [ ]:
"""# read_csv function which is used to read the required CSV file
data = pd.read_csv('Coal Ash.csv')

# display
print("Original 'Coal Ash.csv' CSV Data: \n")
print(data)

# pop function which is used in removing or deleting columns from the CSV files
data.pop('AES Puerto Rico')

# display
print("\nCSV AES Puerto Rico after deleting the column 'year':\n")
print(data)"""

Original 'Coal Ash.csv' CSV Data:

                AES Puerto Rico  17.948232   -66.152032
0        Big Bend Power Station    27.7944     -82.4036
1     C.D. McIntosh Power Plant    28.0809     -81.9256
2     OUC Stanton Energy Center    28.4836     -81.1686
3    Coleto Creek Power Station    28.7087     -97.2083
4              San Miguel Plant    28.7094     -98.4722
..                          ...        ...          ...
295    Syl Laskin Energy Center   47.53015    -92.25007
296             Taconite Harbor   47.53083   -90.911468
297       Lewis & Clark Station    47.6794    -104.1533
298           Healy Power Plant  63.855373  -148.950634
299     Name of Plant \nor Site        Lat         Long

[300 rows x 3 columns]

CSV AES Puerto Rico after deleting the column 'year':

     17.948232   -66.152032
0      27.7944     -82.4036
1      28.0809     -81.9256
2      28.4836     -81.1686
3      28.7087     -97.2083
4      28.7094     -98.4722
..         ...          ...
295   47.53015    -92.25007
296   47.53083   -90.911468
297    47.6794    -104.1533
298  63.855373  -148.950634
299        Lat         Long

[300 rows x 2 columns]

In [ ]:
data = pd.read_csv("Top 5_O Layer - Top5.csv")
data

       SiteID Latitude  Longitude
0         NaN  Degrees    Degrees
1        96.0  31.3146   -87.1166
2       208.0  33.8523   -86.9041
3       288.0  31.2179   -85.8788
4       656.0  33.0992   -86.9976
...       ...      ...        ...
4853  12667.0  42.9064  -110.8838
4854  12731.0  43.6478  -109.6508
4855  12747.0  43.5326  -106.0053
4856  12987.0  42.5699  -109.5625
4857  12990.0  44.9584  -106.2089

[4858 rows x 3 columns]

In [ ]:
import csv
def readLines():
    def conv(s):
        try:
            s=float(s)
        except ValueError:
            pass
        return s

    with open('CoalAshLatLong.csv', 'rU') as data:
        reader = csv.reader(data)
        for row in reader:
            for cell in row:
                y=conv(cell)

                print("Result:", distance)

In [ ]:
import csv
def readLines():
    def conv(s):
        try:
            s=float(s)
        except ValueError:
            pass
        return s

    with open('Top 5_O Layer - Top5.csv', 'rU') as data:
        reader = csv.reader(data)
        for row in reader:
            for cell in row:
                y=conv(cell)

                print("Result:", distance)

In [ ]:
import numpy as np

CSVData = open("CoalAshLatLong.csv")
Array2d_result = np.loadtxt(CSVData, delimiter=",")

print(Array2d_result)

FileNotFoundError: ignored